/**
 * Markdown exporter: templates for summary and sessions views.
 *
 * For audit view, delegates to the existing manifest-markdown-exporter.
 * Summary and sessions use simple hand-built markdown tables.
 */

import type { SummaryResult } from "../queries/summary-query.ts";
import type { SessionRow } from "../queries/sessions-query.ts";

/** Render the summary result as a markdown report. */
export function summaryToMarkdown(summary: SummaryResult): string {
  const cost = summary.estimatedCostUsd > 0
    ? `$${summary.estimatedCostUsd.toFixed(4)}`
    : "unknown";

  const oldest = summary.oldestSession
    ? fmtDate(summary.oldestSession)
    : "—";
  const newest = summary.newestSession
    ? fmtDate(summary.newestSession)
    : "—";

  return [
    `# ckforensics Summary — Last ${summary.periodDays} Days`,
    "",
    `| Metric | Value |`,
    `|--------|------:|`,
    `| Sessions | ${summary.sessionCount} |`,
    `| Input tokens | ${summary.totalInputTokens.toLocaleString()} |`,
    `| Output tokens | ${summary.totalOutputTokens.toLocaleString()} |`,
    `| Cache read tokens | ${summary.totalCacheRead.toLocaleString()} |`,
    `| Total tokens | ${summary.totalTokens.toLocaleString()} |`,
    `| Estimated cost | ${cost} |`,
    `| Files touched | ${summary.filesTouched} |`,
    `| Edit operations | ${summary.editOps} |`,
    `| Oldest session | ${oldest} |`,
    `| Newest session | ${newest} |`,
    "",
    `> Generated by **ckforensics** · ${new Date().toUTCString()}`,
    "",
  ].join("\n");
}

/** Render the sessions list as a markdown table. */
export function sessionsToMarkdown(sessions: SessionRow[]): string {
  if (sessions.length === 0) {
    return "# Sessions\n\n_(no sessions found)_\n";
  }

  const header = [
    "# Sessions",
    "",
    "| Session ID | Project | Started | Model | Events | Cost |",
    "|------------|---------|---------|-------|-------:|-----:|",
  ];

  const rows = sessions.map((s) => {
    const id = s.id.slice(0, 8) + "…";
    const started = s.startedAt ? fmtDate(s.startedAt) : "—";
    const model = s.model ?? "—";
    const cost = s.estimatedCostUsd != null
      ? `$${s.estimatedCostUsd.toFixed(4)}`
      : "—";
    return `| \`${id}\` | ${s.projectSlug} | ${started} | ${model} | ${s.totalEvents} | ${cost} |`;
  });

  return [...header, ...rows, ""].join("\n");
}

function fmtDate(iso: string): string {
  try {
    return new Date(iso).toISOString().slice(0, 16).replace("T", " ") + " UTC";
  } catch {
    return iso;
  }
}
